version: '3'

services:
  redis:
    image: "redis:alpine"
  web:
    build: .
    command: python /code/run.py
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    # restart: always
    build: .
    command: celery -A celery_worker.celery worker -l info
    env_file:
        - ".env"
    volumes:
      - .:/code
    depends_on:
      - redis
#  celery-beat:
#    build: .
#    command: celery -A proj beat -l info
#    volumes:
#      - .:/code
#    depends_on:
#      - redis
