version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: flask-rq-apps:master
    ports:
      - "9300:9300"
    env_file:
      - .env
    volumes:
      - .:/app
    command: flask run -h 0.0.0.0 -p 9300 --reload
    # command: gunicorn app:app -b 0.0.0.0:9300 -k gevent --reload
    depends_on:
      - redis

  rq_dashboard:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: flask-rq-apps:master
    ports:
      - "8900:8900"
    env_file:
      - .env
    volumes:
      - .:/app
    command: rq-dashboard -b 0.0.0.0 -p 8900 --username ${RQ_DASHBOARD_USERNAME} --password ${RQ_DASHBOARD_PASSWORD} -u ${REDIS_URL}
    depends_on:
      - redis

  rq_default:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: flask-rq-apps:master
    env_file:
      - .env
    volumes:
      - .:/app
    command: rq worker -u ${REDIS_URL} --name default
    depends_on:
      - redis

  redis:
    image: redis:5-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"

  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150"
      - "4151"

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171"
